fix(support): #MO-145 fix escalation to redmine
OPEN-ENT-NG/support pull request #15
Opened 2022-08-11 15:09 UTC by vava56754

## Describe your changes
Correction de l'escalade d'un ticket vers Redmine ou l'on rencontrait une erreur de NumberFormatException
## Checklist tests
- [x] Vérifier que l'escalade coté pivot fonctionne
## Issue ticket number and link
MO-145 : https://jira.support-ent.fr/browse/MO-145
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-11 17:07 UTC, JinDouang requested changes

2022-08-11 17:07 UTC, JinDouang commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
> +                    renderError(request, new JsonObject().put("error","Failed to parse integer"));
une badRequest plutôt non ?

2022-08-11 17:07 UTC, JinDouang commented on src/main/java/net/atos/entng/support/enums/BugTracker.java
> +				e.printStackTrace();
indentation espace..

2022-08-11 17:07 UTC, JinDouang commented on src/main/java/net/atos/entng/support/enums/BugTracker.java
> +            Number issueId = 0;
Pourquoi tu l'assignes à 0 ?

2022-08-11 17:07 UTC, JinDouang commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
> +                if(issueId != null){
indentation espace

2022-08-17 14:22 UTC, flmartineau approved these changes

2022-08-17 14:24 UTC, JinDouang approved these changes

2022-08-17 14:28 UTC, merged