feat(media-library): #CO-1763 change attachment directive to media-library
OPEN-ENT-NG/support pull request #19
Opened 2023-03-20 16:20 UTC by Ozen40

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-21 09:38 UTC, qpic-cgi approved these changes

2023-03-21 09:38 UTC, qpic-cgi commented on src/main/resources/public/template/create-ticket.html
> +				<!--<attachments class="support-attachment" apps="['workspace']" ng-model="ticket.newAttachments"></attachments>-->
Tu peux supprimer le code commenté

2023-03-21 09:55 UTC, Ozen40 commented on src/main/resources/public/template/create-ticket.html
> +				<!--<attachments class="support-attachment" apps="['workspace']" ng-model="ticket.newAttachments"></attachments>-->
C'est fait

2023-03-21 09:56 UTC, sjollois requested changes

2023-03-21 09:56 UTC, sjollois commented on src/main/resources/public/ts/controllers/controller.ts
> +			$scope.eventDocuments = angular.element(document.getElementsByTagName("media-library")).scope();
à quoi sert ton eventDocuments ?

2023-03-21 09:56 UTC, sjollois commented on src/main/resources/public/ts/controllers/controller.ts
> +			$scope.ticket.attachments.splice($scope.ticket.attachments.indexOf(removedDocument), 1);
tu ne peux pas utiliser un filter ? c'est plus safe

2023-03-21 09:56 UTC, sjollois commented on src/main/resources/public/ts/controllers/controller.ts
> +			$scope.ticket.attachments.splice($scope.ticket.attachments.indexOf(removedDocument), 1);
et en une ligne c'est fait

2023-03-21 09:56 UTC, sjollois commented on src/main/resources/public/template/create-ticket.html
> +
espace inutile

2023-03-21 09:56 UTC, sjollois commented on src/main/resources/public/template/attachment-add-picture-lightbox.html
> +<lightbox show="addAttachmentLightbox.isOpen" on-close="addAttachmentLightbox.isOpen = false">
pk ça s'appelle "attachment-add-picture...." alors que tu peux ajouter n'importe quel pièce-jointe et pas juste des photos/images ?

2023-03-21 10:18 UTC, qperie reviewed
Je suis Samuel sur ses remarques. Pour le reste c'est ok pour moi

2023-03-21 10:18 UTC, qperie commented on src/main/resources/public/template/attachment-add-picture-lightbox.html
> +            visibility="'protected'"
Pourquoi 'protected' et pas autre chose ? Tu saurais expliquer ce que font les différentes valeurs possibles ?

2023-03-22 08:50 UTC, Ozen40 commented
J'ai apporté les changements que vous m'avez demandés :

- eventDocuments me permet de récupérer les pièces jointes de mon media-library
- j'ai utilisé le filter comme demandé
- j'ai changé le nom de ma lightbox car en effet, elle me permet d'ajouter n'importe quelles pièces jointes

2023-03-22 10:43 UTC, sjollois approved these changes

2023-03-22 13:33 UTC, merged