feat(change-status): #CO-1753 change ticket status from new to open when admin
OPEN-ENT-NG/support pull request #28
Opened 2023-04-13 13:20 UTC by Ozen40

## Describe your changes
If you are a local admin, when you open ticket that has the status "new" it will automatically change the status to "open"
## Checklist tests

- As a local admin, open a ticket with the status "new" and check if the status passed to "open"
- As a user, open a ticket with the status "new" and check if the status is still "new"

## Issue ticket number and link
[CO-1753](https://jira.support-ent.fr/browse/CO-1753)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-13 14:43 UTC, qperie approved these changes

2023-04-13 15:43 UTC, alicedraillard commented on src/main/resources/public/ts/models/Ticket.ts
> +export type Ticket = {
nom du fichier : ticket.model.ts
exemple de model : https://github.com/OPEN-ENT-NG/ressource-aggregator/blob/MED-129/src/main/resources/public/ts/model/resource.model.ts

2023-04-13 15:57 UTC, JinDouang requested changes

2023-04-13 15:57 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +				ticketService.update($scope.ticket.id, <IBodyTicket>{status: model.ticketStatusEnum.OPENED})
Peux-tu utiliser await plutôt que le .then/catch ?

await avec un try catch

2023-04-14 13:07 UTC, alicedraillard commented on src/main/resources/public/ts/models/ticket.model.ts
> +export interface IBodyTicket {
nommage : pourquoi IBodyTicket et pas ITicket ?

2023-04-14 13:14 UTC, qpic-cgi commented on src/main/resources/public/ts/models/ticket.model.ts
> +export interface IBodyTicket {
Body n'est peut-être pas la meilleur formulation en effet, par contre on pourrait l'appeller "ITicketResponse" par exemple, permettant d'appuyer le fait que ce sont des donnés provenant d'une requête API

2023-04-14 13:24 UTC, Ozen40 commented on src/main/resources/public/ts/models/ticket.model.ts
> +export interface IBodyTicket {
J'ai changé en "ITicketResponse" du coup

2023-04-14 13:24 UTC, qpic-cgi commented on src/main/resources/public/ts/services/ticket.service.ts
> +    update: async (ticketId: number, body: IBodyTicket): Promise<AxiosResponse> => {
En lien avec le commentaire précédent d'Alice, il est vrai que ici, tu ne manipule pas le même object qu'à l'instanciation d'un ticket (à l'aide de la méthode build).

Ici, on manipule plutôt des entries d'un formulaire (pour une mise à jour de ticket en l'occurence), il ne faut donc pas qu'il ai le même type.
Ici, on pourrait lui donner le type payload: ITicketPayload.

Je te remet l'exemple du badge pour minibadge: https://github.com/OPEN-ENT-NG/minibadge/blob/dev/src/main/resources/public/ts/models/badge.model.ts

Tu peux voir qu'on retrouve un IBadgeResponse, qui correspond à ma réponse d'API quand je veux récupérer mes badges, ainsi qu'un IBadgePayload, qui correspond à un formulaire pour mettre à jour mon badge.
et c'est 2 interfaces bien distincts ;)

2023-04-14 13:51 UTC, qpic-cgi requested changes

2023-04-14 13:51 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/controller.ts
> +			$scope.changeStatusAfterOpenTicket();
```suggestion
			await $scope.changeStatusAfterOpenTicket();
```
si tu regarde bien, ta fonction "changeStatusAfterOpenTicket" (l.294) est défini en asynchrone, de ce fait, tu dois mettre un await quand tu appels, sinon, ton code va appeler la méthode, puis il va continuer son exécution , sans attendre que la méthode ai fini son traitement !

2023-04-14 13:51 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/controller.ts
> +			await template.open('main', 'view-ticket');
```suggestion
			template.open('main', 'view-ticket');
```

2023-04-14 13:51 UTC, qpic-cgi commented on src/main/resources/public/ts/models/ticket.model.ts
> +}
si je me souviens, ton formulaire de misse a jour de ticket passe un subject: string; en paramètre, non ?
```suggestion
export interface ITicketPayload{
    subject: string;
}
```

2023-04-17 08:05 UTC, qpic-cgi approved these changes

2023-04-17 08:11 UTC, alicedraillard approved these changes

2023-04-17 08:25 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/controller.ts
> +		$scope.openTicket = async function (id) {
ça c'est une fonction fléché, pas une fonction ternaire

2023-04-18 06:21 UTC, JinDouang approved these changes

2023-04-18 07:03 UTC, merged