Fix IDOR security vulnerability on Support module
OPEN-ENT-NG/support pull request #30
Opened 2023-04-14 13:07 UTC by mariusode

## Describe your changes

- Adding SecuredAction on endpoints with exposed resources
- Enriching the OwnerOrLocalAdmin filter with handling resource ids from request body

Note :
- In order to be able to build locally I added a `build-noDocker.sh` script

## Checklist tests
- Reproducing an illegal attempt to access and update the resources that used to be exposed
- Verifying you get rejected.

## Issue ticket number and link
This fixes the three IDOR vulnerabilities on Support module:
https://opendigitaleducation.atlassian.net/browse/WB-1549
https://opendigitaleducation.atlassian.net/browse/WB-1555
https://opendigitaleducation.atlassian.net/browse/WB-1556

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-14 14:40 UTC, juniorode requested changes

2023-04-14 14:40 UTC, juniorode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +			if (ticketIds.isEmpty()) {
Par acquis de conscience il faudrait filtrer les `ticketIds` pour ne garder que sont qui sont `StringUtils.isNotEmpty`

2023-04-14 14:40 UTC, juniorode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +		HashSet<Integer> idsFromBody = new HashSet<>();
pour respecter le principe de "Coding to interfaces, not implementation" il serait mieux d'avoir cette déclaration-là pour `idsFromBody` :

```
final Set<Integer> idsFromBody = new HashSet<>();
```

2023-04-14 14:40 UTC, juniorode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +		if (request.headers().contains("Content-Type") && request.headers().get("Content-Type").equals("application/json")){
L'en-tête content-type peut contenir le charset donc il vaudrait mieux tester la présence de `"application/json" `plutôt que la stricte égalité

2023-04-14 14:40 UTC, juniorode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +				if (body != null && body.containsKey("ids")) {
Est-ce que tu ne pourrais pas juste avoir un champ `id` aussi ?

2023-04-14 14:40 UTC, juniorode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +					idsFromBody.addAll(new HashSet<>(body.getJsonArray("ids").getList()));
Tu n'es pas obligé d'encapsuler la liste renvoyée dans un `HashSet` pour la passer au `addAll`

2023-04-17 08:40 UTC, mariusode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +			if (ticketIds.isEmpty()) {
Les tickets ids sont désormais directement des Integer, donc plus de risque d'avoir des chaînes de caractère vides.

2023-04-17 08:40 UTC, mariusode commented on src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
> +				if (body != null && body.containsKey("ids")) {
J'ai pas rencontré le cas, mais je peux couvrir le cas si ça devait arriver un jour ?

2023-04-17 10:32 UTC, juniorode approved these changes

2023-04-17 14:18 UTC, merged