feat(export-csv): #CO-1757 export tickets to csv
OPEN-ENT-NG/support pull request #35
Opened 2023-04-26 12:48 UTC by Ozen40

## Describe your changes
As an admin, you can now export tickets to CSV
## Checklist tests

- As an admin, click on "export tickets" button and check if the CSV file is correctly filled with ticket information

## Issue ticket number and link
[CO-1757](https://jira.support-ent.fr/browse/CO-1757)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-27 09:32 UTC, BastienBenard commented on src/main/java/net/atos/entng/support/export/CSVExport.java
> +    public HttpServerRequest request;
Vu avec @Ozen40 pour le supprimer

2023-04-27 09:32 UTC, BastienBenard commented on src/main/resources/public/ts/models/ticket.model.ts
>  }
Vu avec @Ozen40 il faut utiliser un autre model pour un payload différent

2023-04-27 09:32 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/controller.ts
> +			ticketService.exportTicketsCSV(<ITicketPayload>{school:"*",sortBy:"modified",order:"DESC"})
Avec le commentaire src/main/resources/public/ts/models/ticket.model.ts tu n'as plus besoin du cast

2023-04-27 09:32 UTC, BastienBenard commented on src/main/resources/public/ts/services/ticket.service.ts
Si tu a le temps, pense a rajouter des tests.

2023-04-27 09:32 UTC, BastienBenard commented on src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
Si tu a le temps, pense a rajouter des tests.

2023-04-27 09:32 UTC, BastienBenard commented on src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
Si tu a le temps, pense a rajouter des tests.

2023-04-27 10:08 UTC, qpic-cgi requested changes

2023-04-27 10:08 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/export/TicketsCSVExport.java
> +        for (int i = 0; i < this.tickets.size(); i++) { //A changer pour un foreach
stream

2023-04-27 10:08 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/export/TicketsCSVExport.java
> +        for (int i = 0; i < this.tickets.size(); i++) { //A changer pour un foreach
@BastienBenard

2023-04-28 09:14 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
> +            ticketServiceSql.listTickets(user, 1, statuses, applicants, schoolId, sortBy, order, 100, PromiseHelper.handler(ticketsPromise));
Je viens d'apprendre que je dois exporter des tickets que j'aurais cochés donc je vais devoir changer ce que j'ai fait

2023-05-05 10:03 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/export/CSVExport.java
> +    public String generate(){
CTRL + ALT + L

2023-05-05 10:05 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
> +    }*/
supprime le com

2023-05-05 10:24 UTC, qpic-cgi requested changes

2023-05-05 10:24 UTC, qpic-cgi commented on src/main/resources/public/ts/services/ticket.service.ts
> +        link.click();
si je te dis que je vois 2 fonctions différentes ici, tu es d'accord avec moi ? :stuck_out_tongue_winking_eye:

2023-05-05 10:24 UTC, qpic-cgi commented on src/main/resources/public/ts/services/ticket.service.ts
> +    },
tu te sers encore de cette fonction ??

2023-05-05 10:24 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
> +    @ResourceFilter(AdmlOfStructures.class)
C'est un bon début pour la sécurité.

MAIS !
si je suis ADML de l'étab 1, avec un ticket 1 => je souhaite exporter le ticket 1 => /tickets/export?structureId=1, {ids: [1]} => retour OK, jusque là pas de PB

Par contre
je tente d'accéder au ticket 2 appartenant à l'étab 2 (auquel je n'ai pas le droit d'accéder normalement) =>
 /tickets/export?structureId=1, {ids: [2]}
=> retour OK, => ce n'est pas souhaitable

je te laisse te creuser la tête pour ça !

2023-05-10 12:35 UTC, Ozen40 commented on src/main/resources/public/ts/services/ticket.service.ts
https://github.com/OPEN-ENT-NG/support/pull/35/files#diff-056052b5d25309091667f637804bb8a1d998092ea2d2eb556beacd7b4608f5b8:~:text=describe(%27TicketService%27%2C%20()%20%3D%3E%20%7B

2023-05-10 13:31 UTC, BastienBenard commented on src/main/java/net/atos/entng/support/export/TicketsCSVExport.java
> +                .forEach(line -> this.value.append(line));
```suggestion
                .filter(Object::nonNull);
                .forEach(line -> this.value.append(line));
```

2023-05-11 09:40 UTC, JinDouang commented on src/main/java/net/atos/entng/support/Support.java
> +		TicketService ticketService = new TicketServiceImpl(ticketServiceNeo4jImpl);
On ne fera pas de serviceFactory pour ce module

On pensera pour cette éventualité en fonction d'une prochaine grosse évolution

2023-05-11 09:40 UTC, JinDouang commented on src/main/java/net/atos/entng/support/Support.java
> +        TicketController ticketController = new TicketController(ticketServiceSql, ticketService, escalationService, userService, storage);
On ne fera pas de serviceFactory pour ce module

On pensera pour cette éventualité en fonction d'une prochaine grosse évolution

2023-05-12 13:18 UTC, JinDouang approved these changes

2023-05-12 13:25 UTC, merged