fix(security): #CO-1774 add several checks on back api for displaying ticket content called event
OPEN-ENT-NG/support pull request #37
Opened 2023-05-09 13:50 UTC by Gregprod33

## Describe your changes
This correction was especially made to secure @Get("/events/:id") API in postman calls. 
Before displaying the ticket, we now check whether the user is SUPER_ADMIN or LOCAL_ADMIN.
If he's SUPER_ADMIN, he can see all the tickets. If he's ADMIN_LOCAL, he can only see the tickets belonging to his structure.
Otherwise, he can only see his own tickets.

To do that, the method listEvents in TicketService was replaced to become getListEvents which now return a future.
Moreover, when this method is called, a new helper TicketEventHelper comes with its method shouldRenderEvent to proceed all the checks.

Dependences added for this project :
 testCompile "org.powermock:powermock-api-mockito2:$powerMockVersion"
 testCompile "org.powermock:powermock-module-junit4:$powerMockVersion"
 testCompile "org.powermock:powermock-module-testng:$powerMockVersion"
 
 In order to use in Unit tests 

## Checklist tests
On postman, log with super admin account and try to access to every created ticket.
With ADMIN_LOCAL account, try to access tickets from the structure you belong to and other structure, which should lead to a 401 code error.
At least, try a random account with no specific function and try to access your tickets or other tickets.
## Issue ticket number and link
[CO-1774](https://jira.support-ent.fr/browse/CO-1774)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-09 14:18 UTC, flmartineau approved these changes

2023-05-09 14:18 UTC, flmartineau commented on src/main/java/net/atos/entng/support/helpers/impl/TicketEventHelperImpl.java
> +        String owner = eventResult.getJsonObject(0).getString("user_id");
Magic strings

2023-05-09 14:18 UTC, flmartineau commented on src/main/java/net/atos/entng/support/helpers/impl/TicketEventHelperImpl.java
> +        String schoolId = eventResult.getJsonObject(0).containsKey("school_id") ? eventResult.getJsonObject(0).getString("school_id") : null;
Ajoute une vérif sur eventResult (eventResult !== null && !eventResult.isEmpty)

2023-05-09 14:53 UTC, Gregprod33 commented on src/main/java/net/atos/entng/support/helpers/impl/TicketEventHelperImpl.java
> +        String owner = eventResult.getJsonObject(0).getString("user_id");
Modifié :)

2023-05-09 14:53 UTC, Gregprod33 commented on src/main/java/net/atos/entng/support/helpers/impl/TicketEventHelperImpl.java
> +        String schoolId = eventResult.getJsonObject(0).containsKey("school_id") ? eventResult.getJsonObject(0).getString("school_id") : null;
Modifié

2023-05-10 09:13 UTC, BastienBenard commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
>      public void getHistorization(final HttpServerRequest request) {
Pas de droit ? Il faudrait rajouter un AUTHENTICATED

2023-05-10 09:13 UTC, BastienBenard commented on src/main/java/net/atos/entng/support/helpers/TicketEventHelper.java
> +}
Il n'y a pas besoin d'interface pour les helpers, puis que tout les méthode sont sensé être statics

2023-05-10 09:13 UTC, Gregprod33 commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
>      public void getHistorization(final HttpServerRequest request) {
C'est fait

2023-05-25 09:08 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/helpers/IModelHelper.java
[IModelHelper](https://github.com/OPEN-ENT-NG/crre/blob/1770e7e367ee2888e1b930472cc6c4a527597555/src/main/java/fr/openent/crre/helpers/IModelHelper.java) provient de CRRE

2023-05-25 09:10 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/helpers/RequestHelper.java
[RequestHelper](https://github.com/OPEN-ENT-NG/minibadge/blob/dev/src/main/java/fr/openent/minibadge/helper/RequestHelper.java#L44) provient de Minibadge

2023-05-25 09:10 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/helpers/StringHelper.java
[StringHelper](https://github.com/OPEN-ENT-NG/crre/blob/1770e7e367ee2888e1b930472cc6c4a527597555/src/main/java/fr/openent/crre/helpers/StringHelper.java) provient de CRRE

2023-05-25 09:12 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/model/IModel.java
[IModel](https://github.com/OPEN-ENT-NG/crre/blob/1770e7e367ee2888e1b930472cc6c4a527597555/src/main/java/fr/openent/crre/model/IModel.java) provient de CRRE

2023-05-25 15:51 UTC, qpic-cgi requested changes

2023-05-25 15:51 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
> +                                this.getClass().getSimpleName())));
Dans ton exception, tu ne log pas le détail de ton erreur. 
Ensuite, ici, si tu as une as une erreur, ton front va rester en pending sans jamais savoir que ton back a en fait fail.

2023-05-25 15:51 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/helpers/FutureHelper.java
> +    }
Evite de ramener du code déprécier dans ton module ^^

2023-05-26 07:14 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/helpers/FutureHelper.java
> +    }
J'ai supprimé ce fichier ça il était utilisé avec l'ancienne méthode mais plus maintenant (en plus il faisait la même chose que mon PromiseHelper)

2023-05-26 07:17 UTC, qpic-cgi approved these changes

2023-05-26 11:50 UTC, merged