feat(select-all): #CO-1756 select all ticket checkbox
OPEN-ENT-NG/support pull request #40
Opened 2023-05-12 15:09 UTC by Ozen40

## Describe your changes
Checkbox that select all tickets
## Checklist tests

## Issue ticket number and link
[CO-1756](https://jira.support-ent.fr/browse/CO-1756)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-12 15:22 UTC, simonchaval approved these changes

2023-05-12 15:22 UTC, simonchaval commented on src/main/resources/public/template/list-tickets.html
>                      </th>
Il faudrait revoir l'indentation de la balise <th> si possible

2023-05-12 15:25 UTC, JinDouang requested changes

2023-05-12 15:25 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +			$scope.tickets.all.forEach((ticket) => ticket.selected = !ticket.selected)
;

2023-05-12 15:25 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +			$scope.tickets.all.forEach((ticket) => ticket.selected = !ticket.selected)
A renommer la fonction car tu ne fais pas que selectAll, tu toggle plutôt

2023-05-12 15:32 UTC, BastienBenard requested changes

2023-05-15 07:57 UTC, Ozen40 commented on src/main/resources/public/template/list-tickets.html
> +                    <input type="checkbox" ng-change="toggleAll()" ng-model="tickets.selected">
Modification ligne 16

2023-05-15 08:19 UTC, merged