fix(file-too-large): #CO-1748 send http error 413
OPEN-ENT-NG/support pull request #53
Opened 2023-06-28 07:45 UTC by Ozen40

## Describe your changes
If you try to escalate a ticket that has a file too large for Jira, it will fail the escalation and send an http 413 error (Payload Too Large).
## Checklist tests

- Escalate a ticket with a file bigger than 10mb and check if it display the error and fail the escalation

## Issue ticket number and link
[CO-1748](https://jira.support-ent.fr/browse/CO-1748)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-06-28 09:58 UTC, JinDouang requested changes

2023-06-28 09:58 UTC, JinDouang commented on src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
> +                            handler.handle(new Either.Left<>(Ticket.PAYLOADTOOLARGE));
Rajoute un log d'erreur aussi avec le résultat du metadata

2023-06-28 09:58 UTC, JinDouang commented on src/main/java/net/atos/entng/support/constants/Ticket.java
> +    public static final String METADATE = "metadata";
erreur typo

2023-06-28 14:14 UTC, qpic-cgi approved these changes

2023-07-05 09:34 UTC, qperie approved these changes

2023-07-05 09:34 UTC, qperie commented on src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
> +                        if (file.getDocument().getJsonObject(Ticket.METADATA).getInteger(Ticket.SIZE) < 10000000) {
Le 10000000 tu peux en faire un constante

2023-07-05 16:55 UTC, JinDouang commented on src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
> +                                    this.getClass().getSimpleName(), "Payload too large, metadata size : " + file.getDocument().getJsonObject(Ticket.METADATA).getInteger(Ticket.SIZE)));
Sécurise ton code

```suggestion
 this.getClass().getSimpleName(), "Payload too large, metadata size : " + file.getDocument().getJsonObject(Ticket.METADATA, new JsonObject()).getInteger(Ticket.SIZE, 0)));
```

2023-07-12 07:15 UTC, merged