feat(sort-structure): #CO-1793 add possibility to sort tickets by structure name
OPEN-ENT-NG/support pull request #56
Opened 2023-08-04 14:21 UTC by Ozen40

## Describe your changes
You can now sort tickets by structure name by clicking on "structure du demandeur"
## Checklist tests

- Click on "structure du demandeur" on check if the tickets are correctly sorted by structure name

## Issue ticket number and link
[CO-1793](https://jira.support-ent.fr/browse/CO-1793)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-08-07 14:55 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/services/impl/TicketServiceNeo4jImpl.java
> +        JsonObject params = new JsonObject().put(Ticket.STRUCTUREIDS, structureIds);
c'est pas une mauvaise chose de gérer le null pointer je pense

2023-08-07 14:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
> +				values.addAll(orderedStructures);
le null pointer peut être cool à gérer !

2023-08-08 09:16 UTC, Ozen40 commented on src/main/java/net/atos/entng/support/controllers/TicketController.java
> +                        ticketService.sortSchoolByName(user.getStructures())
Cela va être fait dans le [CO-1796](https://jira.support-ent.fr/browse/CO-1796)

2023-08-10 06:57 UTC, Ozen40 commented on src/main/resources/public/ts/models/model.ts
> +				if (!!err && !!err.responseJSON && err.responseJSON.error && !!err.responseJSON.error.i18n){
Exemple pris de : https://github.com/opendigitaleducation/entcore/blob/473bc7ea145cde961af7e3155744b56300b1f364/directory/src/main/resources/public/ts/model.ts#L727

2023-08-10 12:20 UTC, qpic-cgi requested changes

2023-08-10 12:20 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +				if (!!err && !!err.responseJSON && err.responseJSON.error && !!err.responseJSON.error.i18n){
```suggestion
				if (!!err && !!err.responseJSON && !!err.responseJSON.error && !!err.responseJSON.error.i18n){
```

2023-08-10 12:20 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +					notify.error('support.error.sort.tickets.by.school.name');
```suggestion
					notify.error(err.responseJSON.error.i18n);
```
?

2023-08-10 12:20 UTC, qpic-cgi commented on src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
> +        } else promise.fail("support.error.sort.school.by.name");
t'aurais pu utiliser ton nouvel enum d'erreurs non ?

2023-08-16 12:21 UTC, qpic-cgi approved these changes

2023-08-17 14:10 UTC, BastienBenard approved these changes

2023-08-17 14:14 UTC, merged