feature(pictures): #CO-1817 check bad request when create ticket
OPEN-ENT-NG/support pull request #78
Opened 2023-12-18 15:52 UTC by Mattox0

## Describe your changes

Currently, if you created a ticket and it returned a bad request, you could no longer create a ticket.
Now, it returns an error, but you can still recreate a ticket.

## Checklist tests

- Custom route POST `/support/ticket` to send a response 400 and try to create two tickets

## Issue ticket number and link

[https://jira.support-ent.fr/browse/CO-1817](https://jira.support-ent.fr/browse/CO-1817)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [X] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-12-18 15:57 UTC, qpic-cgi requested changes

2023-12-18 15:57 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/controller.ts
> +				};
🤔 y'aurait pas moyen de rendre la méthode un peut plus générique, afin qu'on puisse réutiliser cette partie ailleurs ?

2023-12-18 15:57 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +				if(typeof callback === 'function'){
indentation !

2023-12-19 08:41 UTC, Mattox0 commented on src/main/resources/public/ts/models/model.ts
> +				if(typeof callback === 'function'){
j'avais suivi la même indentation que la fonction `escalateTicket` qui se situe en dessous, je change ça

2023-12-19 09:15 UTC, qpic-cgi requested changes

2023-12-19 09:15 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +			if(typeof callback === 'function'){
indentation !

2023-12-19 09:16 UTC, qpic-cgi requested changes

2023-12-19 09:16 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +		.done(function(result){
indentation !

2023-12-19 09:16 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +			if(typeof badRequestCallback === 'function'){
indentation !

2023-12-19 09:16 UTC, qpic-cgi commented on src/main/resources/public/ts/models/model.ts
> +		.e400(function(){
indentation !

2023-12-19 10:23 UTC, qpic-cgi approved these changes

2023-12-19 10:25 UTC, qperie approved these changes

2023-12-19 10:28 UTC, merged